# Generated by Django 2.0.5 on 2018-07-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('KBH', 'Kailash Boys Hostel'), ('Satpura', 'Satpura Hostel'), ('AGH', 'Ambika Girls Hostel'), ('PGH', 'Parvati Girls Hostel')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_school_area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], db_column='12th School Area', max_length=8),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_school_type',
            field=models.CharField(choices=[('Government', 'Government School'), ('Private', 'Private School')], db_column='12th School type', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='religion',
            field=models.CharField(choices=[('Christian', 'Christian'), ('Hinduism', 'Hinduism'), ('Jainism', 'Jainism'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Zoroastrianism', 'Zoroastrianism')], max_length=16),
        ),
    ]
