# Generated by Django 2.0.5 on 2018-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='jee_cat_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
