# Generated by Django 2.0.5 on 2018-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugbranch',
            name='code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='ugbranch',
            name='section',
            field=models.CharField(max_length=8),
        ),
    ]
