# Generated by Django 2.0.5 on 2018-06-20 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='bonafide_country',
            new_name='b_country',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='bonafide_state',
            new_name='b_state',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='correspondence_add',
            new_name='corr_addr',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='fee_waiver_claim',
            new_name='fee_waiver',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_country',
            new_name='int_country',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_pass_year',
            new_name='int_pass_year',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_percentage',
            new_name='int_percentage',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_school_area',
            new_name='int_school_area',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_school_board',
            new_name='int_school_board',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_school_name',
            new_name='int_school_name',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_school_type',
            new_name='int_school_type',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='intermediate_state',
            new_name='int_state',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='jee_AI_rank',
            new_name='jee_ai_rank',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='jee_category_rank',
            new_name='jee_cat_rank',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='nearest_railway_st',
            new_name='nearest_rs',
        ),
        migrations.RenameField(
            model_name='studentinfo',
            old_name='permanent_add',
            new_name='perm_addr',
        ),
        migrations.RenameField(
            model_name='studentmedicalinfo',
            old_name='height_in_cm',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='studentmedicalinfo',
            old_name='any_other_defect',
            new_name='id_mark',
        ),
        migrations.RemoveField(
            model_name='studentfirstfeestatus',
            name='fee_NIT_receipt_no',
        ),
        migrations.RemoveField(
            model_name='studentmedicalinfo',
            name='identification_mark',
        ),
        migrations.AddField(
            model_name='studentfirstfeestatus',
            name='fee_nith_receipt_no',
            field=models.CharField(default='NULL', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='other_defect',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='ug_sem',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='age',
            field=models.SmallIntegerField(),
        ),
    ]
