# Generated by Django 2.0.6 on 2018-07-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='institute',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='date_of_admission',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='jee_cat_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
