# Generated by Django 2.0.5 on 2018-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0002_auto_20180717_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('vvv', 'ddd'), ('KBH', 'Kailash Boys Hostel'), ('Satpura', 'Satpura Hostel'), ('AGH', 'Ambika Girls Hostel'), ('PGH', 'Parvati Girls Hostel')], max_length=16, null=True),
        ),
    ]
