# Generated by Django 2.0.5 on 2018-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0002_auto_20180620_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='father_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='clour_blindness',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='id_mark',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='major_illness',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='other_defect',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='past_mental_illness',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='vision',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
