# Generated by Django 2.0.6 on 2018-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0002_studentinfo_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='date_of_admission',
            field=models.DateField(auto_now=True),
        ),
    ]
