# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0002_auto_20180621_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='corr_addr',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='perm_addr',
            field=models.CharField(max_length=256),
        ),
    ]
