# Generated by Django 2.0.6 on 2018-06-18 06:28

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0002_auto_20180617_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_due', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=100)),
                ('hostel_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=100)),
                ('acdemic_due', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=100)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentbasicinfo',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='due',
            name='roll_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorp_app.StudentBasicInfo', to_field='roll_no'),
        ),
    ]
