# Generated by Django 2.0.6 on 2018-07-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0003_auto_20180716_1530'),
    ]

    operations = [
      
    ]
