# Generated by Django 2.0.5 on 2018-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0003_auto_20180623_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sub_C',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_L',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_P',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sub_T',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='clour_blindness',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='id_mark',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='major_illness',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='other_defect',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='past_mental_illness',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='vision',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
