# Generated by Django 2.0.5 on 2018-06-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0003_auto_20180620_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='id',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ugbranch',
            name='id',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='full_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='ugbranch',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='ugbranch',
            name='full_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ugbranch',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ugbranch',
            name='section',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='ugclass',
            name='full_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ugclass',
            name='id',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ugclass',
            name='name',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
