# Generated by Django 2.0.5 on 2018-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0004_auto_20180621_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfirstfeestatus',
            name='fee_nith_receipt_no',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='b_country',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='b_state',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='corr_addr',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='fee_waiver',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='hostel_name',
            field=models.CharField(choices=[('KBH', 'Kailash Boys Hostel'), ('Satpura', 'Satpura Hostel'), ('Himadri', 'Himadri Boys Hostel'), ('Himgiri', 'Himgiri Boys Hostel'), ('NBH', 'Neelkanth Boys Hostel'), ('MMH', 'Manimahesh Boys Hostel'), ('VBH', 'Vindhyanchal Boys Hostel'), ('DBH', 'Dauladhar Boys Hostel'), ('AGH', 'Ambika Girls Hostel'), ('PGH', 'Parvati Girls Hostel')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_country',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_school_area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], db_column='12th School Area', max_length=8),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_school_name',
            field=models.CharField(db_column='12th School name', max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_school_type',
            field=models.CharField(choices=[('Government', 'Government School'), ('Private', 'Private School')], db_column='12th School type', max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='int_state',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name_eng',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name_hindi',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nearest_rs',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='perm_addr',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_no',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='religion',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='roll_no',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='blood_group',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='clour_blindness',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='id_mark',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='major_illness',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='other_defect',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='past_mental_illness',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentmedicalinfo',
            name='vision',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
