# Generated by Django 2.0.6 on 2018-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0004_remove_studentinfo_reg_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='reg_staff',
            field=models.CharField(default='pradeep', max_length=50),
            preserve_default=False,
        ),
    ]
