# Generated by Django 2.0.6 on 2018-07-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0005_studentinfo_reg_staff'),
    ]

    operations = [
      
    ]
