# Generated by Django 2.0.5 on 2018-06-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0005_auto_20180626_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_code',
            field=models.CharField(max_length=16),
        ),
    ]
