# Generated by Django 2.0.5 on 2018-07-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0006_auto_20180626_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='-------', max_length=8),
        ),
    ]
