# Generated by Django 2.0.6 on 2018-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0007_studentinfo_date_of_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='jee_cat_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
