# Generated by Django 2.0.5 on 2018-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0010_auto_20180706_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='institute',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='aadhar_no',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='contact',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='entry_no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='fee_waiver',
            field=models.CharField(choices=[('Not Claimed', 'Not Claimed'), ('SC/ST/PwD', 'SC/ST/PwD'), ('Income Less than 1 Lakhs', 'Income Less than 1 Lakhs'), ('Income between 1 and 5 Lakhs', 'Income between 1 and 5 Lakhs')], max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('KBH', 'Kailash Boys Hostel'), ('Satpura', 'Satpura Hostel'), ('Himadri', 'Himadri Boys Hostel'), ('Himgiri', 'Himgiri Boys Hostel'), ('NBH', 'Neelkanth Boys Hostel'), ('MMH', 'Manimahesh Boys Hostel'), ('VBH', 'Vindhyanchal Boys Hostel'), ('DBH', 'Dauladhar Boys Hostel'), ('AGH', 'Ambika Girls Hostel'), ('PGH', 'Parvati Girls Hostel')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='jee_cat_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name_hindi',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nearest_rs',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
