# Generated by Django 2.0.5 on 2018-07-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0012_auto_20180708_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='roll_no',
            field=models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='sorp_app.StudentInfo', to_field='roll_no'),
        ),
    ]
