# Generated by Django 2.0.5 on 2018-07-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0013_auto_20180709_0445'),
        ('sorp_app', '0011_auto_20180706_2328'),
    ]

    operations = [
    ]
