# Generated by Django 2.0.6 on 2018-07-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0014_merge_20180709_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='religion',
            field=models.CharField(choices=[('---------', '---------'), ('Christian', 'Christian'), ('Hinduism', 'hinduism'), ('Jainism', 'Jainism'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism')], max_length=16),
        ),
    ]
