# Generated by Django 2.0.5 on 2018-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0014_merge_20180709_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='doc_imp',
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='submitted',
            field=models.CharField(max_length=2),
        ),
    ]
