# Generated by Django 2.0.5 on 2018-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0014_merge_20180709_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='institute',
            field=models.CharField(default='NITH', max_length=16),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_imp',
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='submitted',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='aadhar_no',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_contact',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_contact',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='hostel_name',
            field=models.CharField(blank=True, choices=[('KBH', 'Kailash Boys Hostel'), ('Satpura', 'Satpura Hostel'), ('AGH', 'Ambika Girls Hostel'), ('PGH', 'Parvati Girls Hostel')], default='KBH', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='jee_cat_rank',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='name_hindi',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nearest_rs',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='religion',
            field=models.CharField(choices=[('---------', '---------'), ('Christian', 'Christian'), ('Hinduism', 'Hinduism'), ('Jainism', 'Jainism'), ('Muslim', 'Muslim'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Zoroastrianism', 'Zoroastrianism')], max_length=16),
        ),
    ]
