# Generated by Django 2.0.6 on 2018-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0015_studentinfo_reg_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_staff',
            field=models.CharField(default='pradeep', max_length=50),
        ),
    ]
