# Generated by Django 2.0.6 on 2018-07-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0016_auto_20180714_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='reg_staff',
        ),
    ]
