# Generated by Django 2.0.6 on 2018-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0018_studentinfo_reg_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='institute',
            field=models.CharField(choices=[('NIT Hamirpur', 'NIT Hamirpur'), ('IIIT Una', 'IIIT Una')], default='NIT Hamirpur', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='reg_staff',
            field=models.CharField(max_length=50),
        ),
    ]
