# Generated by Django 2.0.6 on 2018-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0020_auto_20180715_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='institute',
            field=models.CharField(max_length=16),
        ),
    ]
