# Generated by Django 2.0.7 on 2018-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorp_app', '0022_remove_studentinfo_institute'),
        ('sorp_app', '0015_auto_20180715_1402'),
    ]

    operations = [
    ]
